name: sig_shoes
description: Aplicación para distribuidores de delivery
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP Client
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0

  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

  # Permissions
  permission_handler: ^11.2.0

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


dependency_overrides:
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
